services:
  web:
    build: './docker-build/php/'
    ports: 
      - '8006:443'
    volumes: 
      - .:/var/www/places
    links:
      - db:db
    
  db:
    build: './docker-build/mysql/'
    volumes:
      - ~/.docker/mysql:/var/lib/mysql
    ports:
      - '3026:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=iamfree
    
  adminpaneldb:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8076:80'
    links:
      - db:db
  
  